// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id          int64  `json:"id"`
	Account     string `json:"account"`
	AccessToken string `json:"accessToken"`
}

type UserinfoReply struct {
	Id      int64  `json:"id"`
	Account string `json:"account"`
}
