// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: app/ucenter/rpc/ucenter.proto

package ucenter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UcenterClient is the client API for Ucenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UcenterClient interface {
	UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoReply, error)
}

type ucenterClient struct {
	cc grpc.ClientConnInterface
}

func NewUcenterClient(cc grpc.ClientConnInterface) UcenterClient {
	return &ucenterClient{cc}
}

func (c *ucenterClient) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoReply, error) {
	out := new(UserInfoReply)
	err := c.cc.Invoke(ctx, "/user.Ucenter/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UcenterServer is the server API for Ucenter service.
// All implementations must embed UnimplementedUcenterServer
// for forward compatibility
type UcenterServer interface {
	UserInfo(context.Context, *UserInfoReq) (*UserInfoReply, error)
	mustEmbedUnimplementedUcenterServer()
}

// UnimplementedUcenterServer must be embedded to have forward compatible implementations.
type UnimplementedUcenterServer struct {
}

func (UnimplementedUcenterServer) UserInfo(context.Context, *UserInfoReq) (*UserInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (UnimplementedUcenterServer) mustEmbedUnimplementedUcenterServer() {}

// UnsafeUcenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UcenterServer will
// result in compilation errors.
type UnsafeUcenterServer interface {
	mustEmbedUnimplementedUcenterServer()
}

func RegisterUcenterServer(s grpc.ServiceRegistrar, srv UcenterServer) {
	s.RegisterService(&Ucenter_ServiceDesc, srv)
}

func _Ucenter_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UcenterServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Ucenter/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UcenterServer).UserInfo(ctx, req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ucenter_ServiceDesc is the grpc.ServiceDesc for Ucenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ucenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Ucenter",
	HandlerType: (*UcenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfo",
			Handler:    _Ucenter_UserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/ucenter/rpc/ucenter.proto",
}
